### ISSUE TITLE
Should this feedstock depend on xkeyboard-config

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/libxkbcommon-feedstock#19]
### Comment:

I've found that Ubuntu has been pushing more users to default to wayland (at least on new installations).

This has exposed a few problems in the qt package
https://github.com/conda-forge/qt-main-feedstock/issues/117

Mainly, should this feedstock depend on `xkeyboard-config` or should downstream packages be expected to add this dependency.

**Comment by hmaarrfk** [comment]
@pkgw i know you don't maintain this feedstock, but your advice is appreciated.

**Comment by pkgw** [comment]
Yes, I think it makes sense for this feedstock to depend on `xkeyboard-config`. As I understand it, any package that requires `libxkbcommon` is almost surely going to want/need actual keyboard data to load, and depending on `xkeyboard-config` will provide those data in a reliable way that doesn't depend on the host OS. But this is definitely not an area of my expertise!

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender
