### ISSUE TITLE
libxkbcommon-x11.so.0 not provided

### ISSUE THREAD

**Issue by pescobar** [conda-forge/libxkbcommon-feedstock#3]
I am getting this error when trying to execute [https://github.com/MouseLand/suite2p](https://github.com/MouseLand/suite2p) using latest conda

```
QLibraryPrivate::loadPlugin failed on "$HOME/anaconda3/envs/suite2p/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library $HOME/anaconda3/envs/suite2p/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory)"

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

I tried to install this conda package to provide the missing library `libxkbcommon-x11.so.0` but the library is not included in the package.

I suppose I can workaround the problem if I install the system package providing the missing library (rpm libxkbcommon-x11) but I would prefer to use conda. Would it be possible that this package provides the required library `libxkbcommon-x11.so.0` ?

thanks in advance for any help or suggestion.

**Comment by scopatz** [comment]
Is suite2p a conda package?

**Comment by pescobar** [comment]
it's installed with pip. 

You can find here the environment file provided by the developer https://github.com/MouseLand/suite2p/blob/master/environment.yml

and here the installation instructions
https://github.com/MouseLand/suite2p#installation

**Comment by scopatz** [comment]
Yeah, anything installed with pip in a conda environment (esp. with a compiled dependency) is not guaranteed to work.  There should be a conda-forge package for suite2p.

**Comment by pescobar** [comment]
Sure, it would be very convenient to have a conda package for suite2p but this would not solve my  problem. It would still miss the required library `libxkbcommon-x11.so.0` 

do you know if it's possible to provide the library `libxkbcommon-x11.so.0` using conda instead of using system packages? I can try to build my own conda package if I figure out the proper way to do it. Any help or advice is welcome.

Please feel free to close this issue if the conda package `libxkbcommon` cannot provide the required library `libxkbcommon-x11.so.0`

**Comment by scopatz** [comment]
> It would still miss the required library 

I believe that when the conda-package is compiled it will link against `libxkbcommon-x11.so` instead.

**Comment by pescobar** [comment]
thanks for the suggestion. I will give it a try

**Comment by scopatz** [comment]
Excellent! Thanks!

**Comment by pescobar** [comment]
I have realized that this dependency was introduced by pyqt5 installed by pip 
https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041363.html

I found a workaound by downgrading pyqt5 doing `pip install PyQt5==5.11.3` and I reported the issue to the suite2p developers
https://github.com/MouseLand/suite2p/issues/235

**Comment by wxjttxs** [comment]
I tried this command "sudo apt install pyqt5-dev-tools pyqt5-dev" and it sloved the same question.
