### ISSUE TITLE
Binaries break conda-build when ldconfig is run

### ISSUE THREAD

**Issue by epruesse** [conda-forge/libxkbcommon-feedstock#7]
The binaries in this package as of 0.10.0 break conda-build on building a package that runs `ldconfig -n $LIBDIR`.

To reproduce:
```
wget https://anaconda.org/conda-forge/libxkbcommon/0.10.0/download/linux-64/libxkbcommon-0.10.0-he1b5a44_0.tar.bz2
tar xf libxkb*bz2
cd lib
ldconfig -n .
ls -b
```

Results in:
```
\357\310\r
libxkbcommon.so
libxkbcommon.so.0
libxkbcommon.so.0.0.0
libxkbcommon-x11.so
libxkbcommon-x11.so.0
libxkbcommon-x11.so.0.0.0
pkgconfig
```

The first file in turn causes a UnicodeEncodeError in conda build (build.py line 1040) when it's trying to write the info file. It's a symlink to libxkbcommon.so.0. Not sure what's going on.

**Comment by scopatz** [comment]
PRs welcome, if we can figure out what is going on

**Comment by epruesse** [comment]
That's the big if. Took me half the day to get this far from a bioconda package build failing.

Might also want to adjust conda-build so it doesn't just error out, but shows something more informative.

**Comment by epruesse** [comment]
Ok, my local build of glibc HEAD just finished. It works fine with the ldconfig in there. Of course. Because upgrading glibc is the easy fix.

**Comment by hmaarrfk** [comment]
sorry for not responding in 4 years.

Given that these issues somewhat get a little stale, i'm going to close this since I figure that you likely moved on.

However, if you face this again, I would love to be able to help! please open a new issue if that is case.
